services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      servicio-datos:
        condition: service_healthy
      servicio-riesgo:
        condition: service_healthy
    networks:
      - red-incendios

  servicio-datos:
    build: ./servicio-datos
    container_name: servicio-datos
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/docs')"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - red-incendios

  servicio-riesgo:
    build: ./servicio-riesgo
    container_name: servicio-riesgo
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/docs')"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - red-incendios

networks:
  red-incendios:
    driver: bridge